- plugin.xml
Update reference of Cordova-SQLCipher-Adapter to apply the fix for the following PR: 
https://github.com/OutSystems/Cordova-sqlcipher-adapter/pull/4
Issue: https://outsystemsrd.atlassian.net/browse/RNMT-2530
> Updated cordova-sqlcipher-adapter reference

- CHANGELOG.MD
- README.md
- hooks/disableAndroidBackup.js
- plugin.xml
- www/outsystems-secure-sqlite-init.js
Fixes method to fetch the Cipher Local Storage key from the keychain and disables Android Auto Backup for apps using this plugin.
Fixes https://outsystemsrd.atlassian.net/browse/RNMT-1853
This is required in order to ensure the correctness of the mechanism that fetches the encryption key used to cipher the local storage. Also, since Android Auto Backup was backing up encrypted tables, when a new installation was made, the app's data was restored (encrypted with an old key) and the tables could no longer be accessed.
For more information check the support case previously mentioned.
Manual verification was conducted to validate the reported behavior an issue was no longer replicated.
> RNMT-1853 Fixes Cipher Local Storage key fetch mechanism

- CHANGELOG.MD
- plugin.xml
This PR includes the support of 64-bits libraries (provided by the version **0.1.7-OS5 from Cordova-sqlcipher-adapter**).
This new version includes: 
- Two new arch to support 64-bits (arm64-v8a and x86_64)
- Other libs updated to include the latest version from the PR **[RNMT-2669 Cipher Plugin - Support to 64-bits](https://github.com/OutSystems/android-database-sqlcipher/pull/2)**
References https://outsystemsrd.atlassian.net/browse/RNMT-2669
Manual tests have been performed (using **Test Plugins App with Ciphered**, a custom app using **Barcode Scanner + CardIO + Cipher Local Storage** plugin) and a customer app (from Personal Group). **Automatic tests and QA certification are currently on-going.**
> RNMT-2669 Cipher Plugin - Support to 64-bits

- CHANGELOG.MD
- plugin.xml
Updates version of cordova-plugin-secure-storage to 2.6.8-OS
> chore: updates version of cordova-plugin-secure-storage to 2.6.8-OS

- CHANGELOG.MD
- plugin.xml
No longer crashes in Android 10 when the device is not secure. In this case it opens the lock screen settings, similarly to what happened in older versions of Android.
This PR just raises the version of the Key Store Plugin that is used by this plugin.
Fixes https://outsystemsrd.atlassian.net/browse/RNMT-3540
We tried using AndroidX and it seemed to work fine but unfortunately the classes only exist in SDK 28 and newer. Therefore it fails to build in MABS 3 and 4 (and MABS 3 is not obsolete yet). The AndroidX package exists to provide compatibility with older SDK versions.
Manual tests were performed
> RNMT-3540 Cipher Plugin ::: Android 10 Crash

- CHANGELOG.MD
- plugin.xml
- www/outsystems-secure-sqlite-init.js
Handles lock screen authentication failures.
Fixes https://outsystemsrd.atlassian.net/browse/RNMT-3604
This commit raises the used version of the Key Store Plugin. The new version no longer allows the creation of stores when lock screen credentials are requested and said authentication fails for any reason.
This commit also handles these errors when received by this plugin.
*Please also review the error message*
Manual tests were performed
> RNMT-3604 [Key Store] Can set/get/remove after cancel authentication

- CHANGELOG.MD
- plugin.xml
- www/outsystems-secure-sqlite-init.js
Reverts the previous fix.
Raises the used version of the Key Store Plugin.
Fixes https://outsystemsrd.atlassian.net/browse/RNMT-3824
This commit raises the used version of the Key Store Plugin. It mostly does not affect this plugin, but we should raise this to the latest version available.
Manual tests were performed
> RNMT-3824 Errors in the first reads/writes of a Key Store when multiple initializations run simultaneously

- CHANGELOG.md
- plugin.xml
Raises the used version of the Key Store Plugin.
Fixes https://outsystemsrd.atlassian.net/browse/RNMT-3803
Lock screen in Android 10 is no longer shown on first runs.
Manual tests were performed:
- Using Android 5, 9 and 10
- With the keyguard unlocked and locked, thanks to `getWindow().addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED)`
- Tested both Key Store and Ciphered Local Storage Plugins
Built both plugins in MABS 3.3 (target 26) and MABS 6.1 (target 29).
> RNMT-3803 Key Store Plugin ::: Review Lock Screen in Android

- plugin.xml
Raising DisableBackup plugin version after it's update.
With MABS 7 cordova is updated and stops supporting certain cases of requireCordovaModule for JS importing.
The new DisableBackup was changed to be compliant with this
> RMET-309 updating the disableBackup plugin version

- plugin.xml
- www/outsystems-secure-sqlite-init.js
Changed how the plugin fetches it's dependencies which was the cause for both logger errors and the Android 11 unlock error
> RMET-374 Logger update for MABS 7 and Android 11 fixes

- plugin.xml
Raise secure storage version to latest
> RMET-374 - raise secure storage version to 2.6.8-OS6

- CHANGELOG.md
- plugin.xml
- This PR updates the dependency to the `cordova-sqlcipher-adapter` plugin. It also updates the dependency to the latest version of the `cordova-plugin-secure-storage.git`, that we released because of the `metadata` update in the Extensability Configurations for MABS 8.
- The update of `cordova-sqlcipher-adapter` solves the issue in the context.
https://outsystemsrd.atlassian.net/browse/RMET-1191
Tested locally in Android Studio. MABS 7 and 8 working. Also tested with APKs built by MABS.
> RMET-1191 Cipher Plugin - Update adapter dependency

- CHANGELOG.md
- package.json
- plugin.xml
Fixes error messages:
Keystore operation failed, User not authenticated, Key not yet valid. (RMET-1182)
https://outsystemsrd.atlassian.net/browse/RMET-1182
Also related with the PR: https://github.com/OutSystems/cordova-plugin-secure-storage/pull/14
Tested manually.
> RMET-1182 ::: Fix - Ciphered database errors

- CHANGELOG.md
- package.json
- plugin.xml
For iOS 15, on `SecureStorage`'s `init` method, if `ProtectedData` is unavailable, add an observer for the `UIApplicationProtectedDataDidBecomeAvailable` notification that re-triggers init when it becomes available.
https://outsystemsrd.atlassian.net/browse/RPM-2504
iOS
The issue couldn't be replicated.
> RPM-2504 ::: Avoid Keychain's errSecInteractionNotAllowed error on iOS 15

- CHANGELOG.md
- www/outsystems-secure-sqlite-init.js
- `error.indexOf` resulted in an uncaught exception, as there is no `indexOf()` function for the `error` object. Instead, we need to get the `message` first.
- Because of this uncaught exception, an app using the Ciphered Local Storage plugin would be stuck whenever the `error.indexOf` was called in the if-condition.
References: https://outsystemsrd.atlassian.net/browse/RMET-1771
Tested in an app built with MABS 8.1 and returning the migration failed error (forced in the code).
> RMET-1771 Ciphered Plugin - Fixing comparison for migration failed

- CHANGELOG.md
- plugin.xml
Remove the older `OSCore` framework and replace it by the new `OSCommonPluginLib` pod. This is done by updating Keystore to its latest `2.6.8-OS14` version.
A Sample App build was generated to test this PR: https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=a72f543092b132f7b095d673c61c91dc3ae73ab0
https://outsystemsrd.atlassian.net/browse/RPM-3153
> RMET-3153 ::: Replace OSCore by OSCommonPluginLib

- CHANGELOG.md
- plugin.xml
Update `cordova-plugin-secure-storage` to version `2.6.8-OS15`.
To test the issue, a Sample App build for `Ciphered Local Storage` was created. It can be checked [here](https://intranet.outsystems.net/MABS/BuildDetail.aspx?BuildId=8f75bf7b075ed5d7e14e04f9ff796c9dcef5a196).
https://outsystemsrd.atlassian.net/browse/RMET-2062
This is a follow up on [this PR](https://github.com/OutSystems/cordova-plugin-secure-storage/pull/21).
> RMET-2062 ::: iOS ::: Return Empty Result

- CHANGELOG.md
- plugin.xml
- Updates dependency to KeyStore version 2.6.8-OS17
References: https://outsystemsrd.atlassian.net/browse/RMET-2190
Tested MABS 8 and 9 builds, on Android 12, 11, 10, 9 and 8.
> RMET-2190 Ciphered Plugin - Update dependency to KeyStore

- CHANGELOG.md
- package.json
- plugin.xml
- Android
- iOS
- This PR has the purpose of updating SQLite version to `3.40.1`. This means that SQLCipher it self was updated in order to bring a new SQLite version along;
- Version `3.40.1` was chosen to better align with SQLite `3.40.0` used by MABS;
- We couldn't use `3.40.0` exactly because it isn't available on sqlcipher.
To update Android platform we needed to update `android-database-sqlcipher`.
This PR is just an update on the android-database-sqlcipher version reference.
We tested this on real device by:
- Running the sample app as normal;
- Installing the updated version on top of the old one, to test the migration process;
> RMET-2843 ::: SQlite 3.40.1 Update

- CHANGELOG.md
- package.json
- plugin.xml
- Updates dependency to `cordova-plugin-secure-storage` to version 2.6.8-OS23
References: https://outsystemsrd.atlassian.net/browse/RMET-4277
> RMET-4277 - Update dependency KeyStore Cordova plugin
